name: CI

on:
  push:
    branches: [main, "*"]
  pull_request:
    branches: [main, "*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Run tests (if present)
        run: |
          if npm run | grep -q " test"; then
            npm test
          else
            echo "No test script found, skipping tests."
          fi

      - name: Upload build output
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist
